-- Run this once in Supabase Dashboard -> SQL Editor.
-- This table mirrors app notifications. The Python backend inserts with its
-- service-role key; browser clients listen only to their own recipient_id.

create table if not exists public.realtime_notifications (
  id bigint generated by default as identity primary key,
  recipient_id bigint not null,
  subject text not null,
  message text not null,
  channels text not null default 'in_app',
  created_at timestamptz not null default now()
);

alter table public.realtime_notifications enable row level security;

-- IMPORTANT: This existing app uses its own SQLite login tokens, not Supabase
-- Auth JWTs. Do not create an "anon using (true)" policy: that would expose
-- every customer's notifications. Migrate app login to Supabase Auth before
-- enabling browser subscriptions in production.

alter table public.realtime_notifications replica identity full;
alter publication supabase_realtime add table public.realtime_notifications;
